import { Product, Category, Testimonial } from "./types";

export const CATEGORIES: Category[] = [
  {
    id: "all",
    name: "All Collections",
    description: "Discover our entire catalog of curated designs.",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=600",
    itemCount: 8,
  },
  {
    id: "apparel",
    name: "Apparel",
    description: "Sartorial minimalism with premium, breathable natural fibers.",
    image: "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&q=80&w=600",
    itemCount: 3,
  },
  {
    id: "accessories",
    name: "Accessories",
    description: "Finely calibrated accents to elevate your daily lines.",
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=600",
    itemCount: 2,
  },
  {
    id: "footwear",
    name: "Footwear",
    description: "Architectural profiles designed with cloud-like responsive soles.",
    image: "https://images.unsplash.com/photo-1549298916-b41d501d3772?auto=format&fit=crop&q=80&w=600",
    itemCount: 2,
  },
  {
    id: "fine-home",
    name: "Fine Home",
    description: "Slow-made items honoring raw textures and quiet aesthetics.",
    image: "https://images.unsplash.com/photo-1581641830607-400af182270b?auto=format&fit=crop&q=80&w=600",
    itemCount: 1,
  },
];

export const PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "Classic Wool Trench Coat",
    price: 280,
    category: "apparel",
    image: "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 124,
    tag: "Seasonal Pick",
    description: "Sartorial precision defined by a premium heavyweight virgin wool blend, structured shoulders, and an elegant wrap tie belt. Designed to transcend seasons.",
    colors: ["Camel", "Obsidian Black", "Sage Gray"],
    sizes: ["XS", "S", "M", "L", "XL"],
  },
  {
    id: "p2",
    name: "Symmetrical Chronograph Watch",
    price: 195,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1524592094714-0f0654e20314?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 88,
    tag: "Best Seller",
    description: "Sleek surgical-grade stainless steel case housing a high-precision Japanese quartz movement, paired beautifully with a full-grain vegetable-tanned leather strap.",
    colors: ["Gold Case", "Silver Case", "Onyx Case"],
    sizes: ["One Size"],
  },
  {
    id: "p3",
    name: "Raw Leather Desert Boot",
    price: 220,
    category: "footwear",
    image: "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&q=80&w=600",
    rating: 4.7,
    reviewsCount: 56,
    tag: "Limited Run",
    description: "Sourced with traceably harvested grain leathers. Intentionally styled with clean geometric stitching, resting on a supportive custom natural crepe sole.",
    colors: ["Oak Brown", "Slate Blue", "Charcoal Black"],
    sizes: ["38", "39", "40", "41", "42", "43"],
  },
  {
    id: "p4",
    name: "Linen Casual Overshirt",
    price: 110,
    category: "apparel",
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=600",
    rating: 4.6,
    reviewsCount: 204,
    tag: "New In",
    description: "Woven entirely with natural, organic high-staple Belgian flax fibers. Exceptionally light, naturally slubbed, and perfectly relaxed for elegant summer twilights.",
    colors: ["Sand White", "Olive Drab", "Sienna Brown"],
    sizes: ["S", "M", "L", "XL"],
  },
  {
    id: "p5",
    name: "Sculpted Ceramic Terracotta Vase",
    price: 85,
    category: "fine-home",
    image: "https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 42,
    tag: "Artisanal Piece",
    description: "Individually hand-thrown sandstone ceramic stoneware featuring a rough-textured slip glaze. Crafted by local clay artisans in low-emission small-batch kilns.",
    colors: ["Natural Terracotta", "Alabaster White"],
    sizes: ["Medium (24cm)", "Large (35cm)"],
  },
  {
    id: "p6",
    name: "Minimalist Leather Backpack",
    price: 245,
    category: "accessories",
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&q=80&w=600",
    rating: 4.8,
    reviewsCount: 93,
    tag: "Editors' Pick",
    description: "Water-resistant oiled canvas lining enclosed by soft, buttery bridle leather. Comfortably houses a 15-inch laptop inside a padded wool-lined dedicated compartment.",
    colors: ["Tan Accent", "Full Black"],
    sizes: ["One Size"],
  },
  {
    id: "p7",
    name: "Tailored Pleated Trouser",
    price: 145,
    category: "apparel",
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&q=80&w=600",
    rating: 4.5,
    reviewsCount: 71,
    tag: "Trending",
    description: "A comfortable modern staple. Styled with single reverse pleats and a relaxed taper down to a clean crop. Woven from breathable stretch wool-twill.",
    colors: ["Slate Charcoal", "Sandstone Beige"],
    sizes: ["30", "31", "32", "33", "34", "36"],
  },
  {
    id: "p8",
    name: "Architectural Knit Trainer",
    price: 175,
    category: "footwear",
    image: "https://images.unsplash.com/photo-1491553895911-0055eca6402d?auto=format&fit=crop&q=80&w=600",
    rating: 4.9,
    reviewsCount: 112,
    tag: "Ecological",
    description: "Spun from breathable eucalyptus and merino tree fibers, offering complete odor-resistance. Set atop an lightweight sugarcane EVA foam cushion block.",
    colors: ["Stone White", "Sage Knit", "Deep Forest"],
    sizes: ["40", "41", "42", "43", "44", "45"],
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "t1",
    name: "Elena Rostova",
    role: "Architect & Creative Lead",
    quote: "The wool coat is an absolute masterpiece of understated tailoring. Beautiful texture, comfortable weight, and structural lines that hold their form. Truly slow fashion at its finest.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "t2",
    name: "Marcus Sterling",
    role: "Visual Consultant",
    quote: "LUMINA's design discipline is incredible. The minimal timepiece is lightweight, is styled flawlessly with everything, and keeps immaculate precision. Service was also highly refined.",
    rating: 5,
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=150",
  },
  {
    id: "t3",
    name: "Sienna Vance",
    role: "Co-Founder, Studio Note",
    quote: "Every single purchase feels distinct and highly curated. The ceramic stoneware vases have become absolute highlights of my studio. They balance beautifully with negative space.",
    rating: 4.9,
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150",
  },
];
